# Generated by Django 5.2.16 on 2026-08-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField(help_text="Karta ichida ko'rinadigan qisqa matn")),
                ('body', models.TextField(help_text="To'liq post matni (HTML ruxsat etiladi)")),
                ('read_minutes', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thread posti',
                'verbose_name_plural': 'Thread postlari',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontakt xabari',
                'verbose_name_plural': 'Kontakt xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsideWorldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Masalan: layers, brain', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('text', 'Oddiy matn karta'), ('list', "Ro'yxat karta")], default='text', max_length=10)),
                ('body_text', models.TextField(blank=True, help_text="card_type=text bo'lsa shu ishlatiladi")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Inside World kartasi',
                'verbose_name_plural': 'Inside World kartalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: The Spark', max_length=100)),
                ('year', models.CharField(help_text='Masalan: 2019', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Journey yozuvi',
                'verbose_name_plural': 'My Journey',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio kategoriyasi',
                'verbose_name_plural': 'Portfolio kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Islom Farkhodov', max_length=150)),
                ('display_name', models.CharField(default='Hanzo-Dev', help_text="Sidebar'da katta harflar bilan chiqadigan nom", max_length=100)),
                ('title', models.CharField(default='Web Developer', help_text="Ism ostidagi badge, masalan 'Web Developer'", max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Masalan: Uzbekistan, Tashkent city', max_length=150)),
                ('about_intro', models.TextField(blank=True, help_text="About Me bo'limidagi birinchi paragraflar")),
                ('about_extra', models.TextField(blank=True, help_text="Qo'shimcha paragraf (ixtiyoriy)")),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('brain', 'AI / Miya'), ('code', 'Kod'), ('laptop-code', 'Noutbuk'), ('palette', "Dizayn cho'tkasi"), ('rocket', 'Raketa'), ('device-mobile', 'Telefon')], default='code', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Xizmat (What I Do)',
                'verbose_name_plural': 'Xizmatlar (What I Do)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hanzo-Dev', max_length=100)),
                ('favicon', models.ImageField(blank=True, help_text='Brauzer tab belgisi (.ico yoki .png, kvadrat)', null=True, upload_to='site/')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(blank=True, help_text="Fon rasmi (bo'sh qoldirilsa standart gradient ishlatiladi)", null=True, upload_to='site/')),
                ('accent_color', models.CharField(default='#2f6bff', help_text='Asosiy rang (hex), masalan #2f6bff', max_length=7)),
                ('telegram_bot_token', models.CharField(blank=True, help_text="Ixtiyoriy: .env o'rniga shu yerdan ham sozlash mumkin", max_length=200)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site sozlamalari',
                'verbose_name_plural': 'Site sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Masalan: Frontend, Backend', max_length=50)),
                ('items', models.CharField(help_text='Vergul bilan: React, Next.js, Vue, TailwindCSS, SASS', max_length=300)),
                ('level_percent', models.PositiveIntegerField(default=80, help_text='Progress bar foizi (0-100)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill guruhi',
                'verbose_name_plural': 'Skill guruhlari (My Skills)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('threads', 'Threads'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('twitter', 'X / Twitter'), ('youtube', 'YouTube'), ('other', 'Boshqa')], max_length=20)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — umumiy sayt izohi", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blogpost')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsideWorldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('bold_part', models.CharField(blank=True, help_text="Qalin qism, masalan 'Sonar AI'", max_length=100)),
                ('rest_text', models.CharField(blank=True, help_text="Qolgan matn, masalan '— AI chat platform...'", max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.insideworldcard')),
            ],
            options={
                'verbose_name': 'Inside World qatori',
                'verbose_name_plural': 'Inside World qatorlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(upload_to='portfolio/')),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.portfoliocategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag')),
            ],
            options={
                'verbose_name': 'Portfolio loyihasi',
                'verbose_name_plural': 'Portfolio loyihalari',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.project')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi',
                'verbose_name_plural': 'Loyiha rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.tag'),
        ),
    ]
