# Generated by Django 5.2.17 on 2026-08-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0, help_text='Tabiy (real) sayt tashriflari — avtomatik oshadi')),
                ('visits_boost', models.PositiveIntegerField(default=0, help_text="Ko'rsatiladigan raqamni sun'iy oshirish uchun qo'shiladigan qiymat")),
            ],
            options={
                'verbose_name': 'Sayt statistikasi',
                'verbose_name_plural': 'Sayt statistikasi',
            },
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "O'quvchi kategoriyasi",
                'verbose_name_plural': "O'quvchi kategoriyalari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Masalan: Full Stack Developer', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('icon', models.CharField(choices=[('code', 'Kod </>'), ('server', 'Server'), ('palette', "Dizayn cho'tkasi"), ('rocket', 'Raketa'), ('brain', 'AI / Miya'), ('layers', 'Layers'), ('bolt', 'Chaqmoq')], default='code', max_length=30)),
                ('accent_color', models.CharField(default='#7c5cff', help_text='Karta ustidagi ikon foni (hex), masalan #7c5cff', max_length=7)),
                ('skills', models.CharField(blank=True, help_text='Vergul bilan: Python, Django, Vue.js', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': 'Mening Jamoam',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_boost',
            field=models.PositiveIntegerField(default=0, help_text="Ko'rsatiladigan ko'rishlar sonini sun'iy oshirish uchun qo'shiladigan qiymat"),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text="Tabiy (real) ko'rishlar soni — avtomatik oshadi"),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('role', models.CharField(help_text='Masalan: Frontend Student', max_length=100)),
                ('skills', models.CharField(blank=True, help_text='Vergul bilan: HTML, CSS, JavaScript', max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('portfolio_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.studentcategory')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "Mening O'quvchilarim",
                'ordering': ['order'],
            },
        ),
    ]
