# Generated by Django 5.2.17 on 2026-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitestats_studentcategory_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Shaxsiy portfolio yoki loyiha havolasi'),
        ),
    ]
