# Generated by Django 5.2.17 on 2026-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cube_rotation_seconds',
            field=models.PositiveIntegerField(default=40, help_text="About Me sahifasidagi 3D skill kubning bir to'liq (360°) aylanish vaqti, soniyada"),
        ),
    ]
